[application]
name = "xmpp-client"

default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "xmpp-client"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]
index_on_404 = true

[web.resource]
style = ["input.css"]
script = []

[web.resource.dev]
style = ["input.css"]
script = []
